### Fullname: Võ Thanh Hiệp
### Student ID: 21127275
### Class: 21CLC03

# 1) Algorithms

## Gram – Schmidt
### Let a square matrix A with n columns.
  - **Step 1:** Let setU includes n vectors by column in matrix A.
  - **Step 2:** Let setV includes n vector-Vs:
      -  **Step 2.1:** Let i <- 0
      -  **Step 2.2:** Let V[i] <- U[i]
      -  **Step 2.3:** Let j <- 0
      -  **Step 2.4:** V[i] <- V[i] - ((U[i] * V[j]) / (V[j] * V[j])) * V[j]
      -  **Step 2.5:** j <- j + 1
      -  **Step 2.6:** if j < i, goto Step 2.4
      -  **Step 2.7:** if i < n, goto Step 2.2
 - **Step 3:** Let setQ includes n vector-Qs:
      -  **Step 3.1:** Q[i] <- V[i] / (norm of V[i])

## QR Decomposition
 - **Step 1:** Generate matrix Q from n vectors in setQ by Column
 - **Step 2:** Generate transpose matrix Q from matrix Q
 - **Step 3:** Multiple transpose matrix Q by matrix A, having matrix R
 - **Step 4:** Print matrix A, matrix Q and matrix R
 - **Step 5:** End.

In [1]:
def printMatrix(Matrix):
    nRow = len(Matrix)
    for i in range(nRow - 1):
        print(Matrix[i])
    print(Matrix[nRow - 1], end="")
    print()
    
def inputMatrix():
    n = int(input("Enter n (dim of matrix):"))
    
    Matrix = []
    for i in range(n):
        line = []
        for j in range(n):
            cell = int(input("Enter the value in cell [" + str(i + 1) + "][" + str(j + 1) + "]:"))
            line.append(cell)
        Matrix.append(line)
    
    return Matrix

In [2]:
def getVectorByColumn(Matrix, row, column):
    Set = []
    for i in range(column):
        vector = []
        for j in range(row):
            vector.append(Matrix[j][i])
        Set.append(vector)
        
    return Set

In [3]:
def dotProduct(fVector, sVector):
    if len(fVector) != len(sVector):
        return "Cannot dot"
    
    result = 0
    n = len(fVector)
    for i in range(n):
        result += fVector[i] * sVector[i]
        
    return result

In [4]:
def norm(vector):
    result = 0
    n = len(vector)
    for i in range(n):
        result += vector[i]**2
        
    return result**(1/2)

In [5]:
def multipleVectorAndNumber(vector, a):
    result = []
    n = len(vector)
    for i in range(n):
        temp = vector[i] * a
        result.append(temp)
        
    return result

In [6]:
def addTwoVectors(vector1, vector2):
    Res_Vector = []
    if len(vector1) != len(vector2):
        print("Cannot add two vectors with different lengths")
        return
    
    length = len(vector1)
    for i in range(length):
        Res_Vector.append(vector1[i] + vector2[i])
        
    return Res_Vector

In [7]:
def generateMatrixFromSetOfColumnVectors(setVector):
    n = len(setVector)
    Matrix = []
    
    for i in range(n):
        line = []
        for j in range(n):
            temp = setVector[j][i]
            line.append(temp)
        Matrix.append(line)
        
    return Matrix

In [8]:
def transposeMatrix(matrix):
    n = len(matrix)
    transpose_matrix = []
    
    for i in range(n):
        line = []
        for j in range(n):
            line.append(matrix[j][i])
        transpose_matrix.append(line)
            
    return transpose_matrix

In [9]:
def dotProduct(fVector, sVector):
    if len(fVector) != len(sVector):
        return "Cannot dot"
    
    result = 0
    for i in range(len(fVector)):
        result += fVector[i] * sVector[i]
        
    return result

In [10]:
def getColumn(Matrix, pColumn):
    if pColumn > len(Matrix[0]):
        return 'Invalid! Column position is not exists'
    
    row = len(Matrix)
    result = []
    for i in range(row):
        result.append(Matrix[i][pColumn])
        
    return result

In [11]:
def isValidToMultiple(A, B):
    columnA = len(A[0])
    rowB = len(B)
    
    if columnA == rowB:
        return True
    return False

def multiple2Matrixs(A, B):
    if isValidToMultiple(A, B) == False:
        return 'Invalid! Cannot multiple'
    
    result = []
    row = len(A)
    column = len(B[0])
    
    for i in range(row):
        line = []
        for j in range(column):
            columnB = getColumn(B, j)
            line.append(dotProduct(A[i], columnB))
        result.append(line)
        
    return result

In [12]:
def GramSchmidtProcess(setU):
    setV = []
    n = len(setU)
    for i in range(n):
        v = setU[i]
        for j in range(i):
            tempV = setV[j]
            temp = - dotProduct(setU[i], setV[j]) / norm(setV[j])**2
            tempV = multipleVectorAndNumber(tempV, temp)
            v = addTwoVectors(v, tempV)
        setV.append(v)
        
    setQ = []
    for i in range(n):
        q = multipleVectorAndNumber(setV[i], 1.0/norm(setV[i]))
        setQ.append(q)

    return setQ

In [13]:
def makeClear(Matrix):
    row = len(Matrix)
    column = len(Matrix[0])
    
    for i in range(row):
        for j in range(column):
            if abs(Matrix[i][j]) < 0.000001:
                Matrix[i][j] = 0

def decompositionQR(Matrix):
    n = len(Matrix)
    setU = getVectorByColumn(Matrix, n, n)
    setQ = GramSchmidtProcess(setU)
    
    matrixQ = generateMatrixFromSetOfColumnVectors(setQ)
    transpose_matrixQ = transposeMatrix(matrixQ)
    matrixR = multiple2Matrixs(transpose_matrixQ, Matrix)
    
    makeClear(matrixQ)
    makeClear(matrixR)
    
    return matrixQ, matrixR

In [14]:
A = inputMatrix()
printMatrix(A)

Enter n (dim of matrix):3
Enter the value in cell [1][1]:1
Enter the value in cell [1][2]:1
Enter the value in cell [1][3]:1
Enter the value in cell [2][1]:2
Enter the value in cell [2][2]:-2
Enter the value in cell [2][3]:2
Enter the value in cell [3][1]:1
Enter the value in cell [3][2]:1
Enter the value in cell [3][3]:-1
[1, 1, 1]
[2, -2, 2]
[1, 1, -1]


In [15]:
Q, R = decompositionQR(A)

print("Matrix A: ")
printMatrix(A)
print()

print("Matrix Q: ")
printMatrix(Q)
print()

print("Matrix R: ")
printMatrix(R)

Matrix A: 
[1, 1, 1]
[2, -2, 2]
[1, 1, -1]

Matrix Q: 
[0.4082482904638631, 0.5773502691896257, 0.7071067811865474]
[0.8164965809277261, -0.5773502691896256, 0]
[0.4082482904638631, 0.5773502691896257, -0.7071067811865476]

Matrix R: 
[2.4494897427831783, -0.816496580927726, 1.632993161855452]
[0, 2.309401076758503, -1.1547005383792512]
[0, 0, 1.414213562373095]


##  Functions describe:
 1. **decompositionQR:** decompositing from matrix A to matrix Q multiple with matrix R
 2. **makeClear:** if any cell in matrix have value 0 in dynamic float such as -3.24358459324e-19, reassign it to value 0. 0
 3. **GramSchmidtProcess:** calculate orthonormal set q from set of vector u
 4. **multiple2Matrixs:** multiple matrix A by matrix B
 5. **isValidToMultiple:** if column of matrix A is equal row of matrix B, return True. Otherwise, return False.
 6. **getColumn:** return a vector by column at the position pColumn in Matrix
 7. **multipleVectorAndNumber:** multiple each elements in vector by number
 8. **norm:** calculate the norm of vector
 9. **dotProduct:** calculate dot product of 2 vectors
 10. **getVectorByColumn:** get set of vector from matrix by column
 11. **transposeMatrix:** generate transpose matrix from original matrix
 12. **generateMatrixFromSetOfColumnVectors:** generate matrix from set of column vectors
 13. **addTwoVectors:** add first vector by second vector
 14. **inputMatrix:** input matrix from key board
 15. **printMatrix:** print matrix 

# 2) EXTEND

In [16]:
import numpy as np

A = np.array(A)

Q, R = np.linalg.qr(A)

print("Matrix A:")
print(A)
print()

print("Matrix Q:")
print(Q)
print()

print("Matrix R:")
print(R)

Matrix A:
[[ 1  1  1]
 [ 2 -2  2]
 [ 1  1 -1]]

Matrix Q:
[[-4.08248290e-01  5.77350269e-01 -7.07106781e-01]
 [-8.16496581e-01 -5.77350269e-01 -5.37546367e-17]
 [-4.08248290e-01  5.77350269e-01  7.07106781e-01]]

Matrix R:
[[-2.44948974  0.81649658 -1.63299316]
 [ 0.          2.30940108 -1.15470054]
 [ 0.          0.         -1.41421356]]


## Comparing results
    The results of algorithm in Topic 1 and numpy in Topic 2 (extend) are the same

## QR decomposition applications

 1. **Solving linear systems:** QR decomposition can be used to solve linear systems of equations efficiently. By decomposing the coefficient matrix into QR form, the system can be rewritten as a triangular system, which is easier to solve. This method is particularly useful for solving overdetermined systems (more equations than variables) in a least squares sense.

 2. **Eigenvalue computation:** QR decomposition is commonly used to compute the eigenvalues of a matrix. The QR algorithm, which repeatedly applies QR decomposition to a matrix, converges to the eigenvalues and eigenvectors of the matrix. This algorithm is widely used in numerical linear algebra for eigenvalue computations.

 3. **Least squares regression:** QR decomposition can be utilized for solving least squares regression problems. Given a set of data points and a model, QR decomposition can provide an efficient way to find the coefficients of the model that best fit the data. This is particularly useful when dealing with large datasets or when the matrix of the regression problem is ill-conditioned.

 4. **Matrix inversion:** QR decomposition can be employed to compute the inverse of a matrix. By decomposing the matrix into QR form, the inverse can be computed by solving a series of triangular systems. This approach is particularly useful when the matrix is sparse or ill-conditioned.

 5. **Signal processing:** QR decomposition can be used in signal processing applications such as digital filtering and signal compression. It allows for efficient decomposition of matrices and can facilitate operations such as filtering, noise reduction, and compression.

 6. **Orthogonalization:** QR decomposition can be utilized to orthogonalize a set of vectors. Given a set of linearly dependent vectors, QR decomposition can be used to find an orthogonal set of vectors that spans the same subspace. This is particularly useful in applications such as signal processing, image compression, and data analysis.

 7. **Matrix rank estimation:** QR decomposition can provide an estimate of the rank of a matrix. The rank of a matrix corresponds to the maximum number of linearly independent rows or columns. By examining the diagonal elements of the R matrix, one can determine the rank of the original matrix.